[build]
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/ppeetteerrs/obsidian-zola.git __site && python3 -c \"import re; f=open('__site/utils.py','r+'); s=f.read(); s=s.replace('PASTEL_COLORS[top_nodes[url]] if url in top_nodes else None','None'); f.seek(0); f.write(s); f.close()\" && sed -i '/___LANDING_BUTTON___/d' __site/zola/templates/index.html && __site/run.sh"
publish = "public"

[build.environment]
LANDING_BUTTON = ""
LANDING_DESCRIPTION = ""
LANDING_PAGE = ""
LANDING_TITLE = ""
PYTHON_VERSION = "3.8"
REPO_URL = "https://github.com/RNunez-HOB/obsidian.git"
SITE_TITLE = "Public notes"
SITE_TITLE_TAB = ""
SITE_URL = "https://rnobsidian.netlify.app/"
TIMEZONE = "Asia/Hong_Kong"
ZOLA_VERSION = "0.15.2"
SORT_BY = "title"
GANALYTICS = ""
SLUGIFY = "y"
HOME_GRAPH = "y"
PAGE_GRAPH = "y"
SIDEBAR_COLLAPSED = ""
FOOTER = ""
ROOT_SECTION_NAME = "main"
GRAPH_OPTIONS = """
{
    nodes: {
        shape: "dot",
        color: isDark() ? "#8c8e91" : "#dee2e6",
        font: {
            face: "Inter",
            color: isDark() ? "#c9cdd1" : "#616469",
            strokeColor: isDark() ? "#c9cdd1" : "#616469",
        },
        scaling: {
            label: {
                enabled: true,
            },
        },
    },
    edges: {
        color: isDark() ? "#8c8e91" : "#dee2e6",
        width: 0.8,
        smooth: {
            enabled: false,
        },
        hoverWidth: 4,
    },
    interaction: {
        hover: true,
    },
    height: "100%",
    width: "100%",
    physics: {
        solver: "repulsion",
    },
}
"""